Repository chipsalliance/caliptra-rtl, pull requests merged in 2024-04, with the labels that each got.

#474 Updating DBG_MANUF_SERVICE_REG description with newly allocated bit
  src/soc_ifc/rtl/soc_ifc_external_reg.rdl
Labels: documentation

#492 [UVM] Fix for a regression failure caused by cycle-inaccurate FSM prediction logic in TB
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_execute_execute.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_lock_lock.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/registers/soc_ifc_reg_cbs_mbox_csr_mbox_unlock_unlock.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/src/soc_ifc_predictor.svh
Labels: regression

#498 Update seed name for test to randomize kv entries
  src/integration/test_suites/smoke_test_kv_crypto_flow/smoke_test_kv_crypto_flow.c
Labels: enhancement

#495 [Docs] Update synchronizer modification language and add rvsyncss to table
  docs/CaliptraIntegrationSpecification.md
Labels: documentation

#414 Add Pull Request Workflow
  .github/scripts/file_hash.sh
  .github/scripts/license_header_check.sh
  .github/scripts/pr_rdl_check.sh
  .github/scripts/stamp_repo.sh
  .github/workflow_metadata/README.md
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  .github/workflows/build-test-verilator.yml
  .github/workflows/doc-gen.yml
  .github/workflows/interactive-debugging.yml
  .github/workflows/pre-run-check.yml
  .github/workflows/pull_request.yml
  README.md
  src/integration/stimulus/testsuites/uvmf_caliptra_top_promote_regression.yml
Labels: Environment

#499 [ENV] Add an aggregated status check for all Verilator matrix tests
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  .github/workflows/build-test-verilator.yml
Labels: enhancement, Environment

#478 [UVM] Update UVM ROM test with bringup fixes, infra to test latest public builds, auto-extract PK values
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  src/integration/tb/caliptra_top_tb_services.sv
  src/integration/test_suites/fw_test_rom/fw_test_rom.makefile
  src/integration/uvmf_caliptra_top/uvmf_template_output/project_benches/caliptra_top/tb/sequences/src/caliptra_top_rom_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/bringup/soc_ifc/soc_ifc_env_reset_sequence_base.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/bringup/soc_ifc/soc_ifc_env_rom_bringup_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_dlen_underflow_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_rom_fw_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc_env_top_mbox_rst_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/src/soc_ifc_predictor.svh
Labels: regression
