Repository chipsalliance/caliptra-rtl, pull requests merged in 2024-03, with the labels that each got.

#449 Update CaliptraIntegrationSpecification.md
  docs/CaliptraIntegrationSpecification.md
Labels: documentation

#427 UVM: Fix some failing scenarios
  src/hmac/uvmf_2022/uvmf_template_output/project_benches/HMAC/tb/testbench/hdl_top.sv
  src/integration/test_suites/libs/riscv_hw_if/link.ld
  src/integration/test_suites/smoke_test_ras/smoke_test_ras.ld
  src/sha512/uvmf_sha512/uvmf_template_output/project_benches/SHA512/tb/testbench/hdl_top.sv
Labels: regression

#462 Lint fix to resolve synthesis issue for SHA512 masked IP
  src/sha512_masked/rtl/sha512_masked_defines_pkg.sv
Labels: bug

#407 Fix typos from regression test lists
  src/integration/stimulus/L0_regression.yml
  src/integration/stimulus/testsuites/caliptra_top_nightly_directed_regression.yml
Labels: Environment, regression

#463 Revert PR 438 with shortened SHA test vector
  src/integration/test_suites/smoke_test_sha_accel/smoke_test_sha_accel_vectors.s
Labels: enhancement

#468 [SOC_IFC_TB] Initialize mailbox RAM in unittest
  src/soc_ifc/tb/soc_ifc_tb.sv
Labels: regression

#467 [UVM] Fix error detection in certain error injection tests
  src/integration/test_suites/caliptra_rt/caliptra_rt.c
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/cptra/soc_ifc_env_cptra_mbox_handler_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_dlen_overflow_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_dlen_underflow_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_max_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_min_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_rand_fw_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_rand_pauser_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_real_fw_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_reg_axs_invalid_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_rom_fw_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sequence_base.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sha_accel_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sram_double_bit_flip_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_uc_reg_access_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/src/soc_ifc_predictor.svh
Labels: regression

#460 Fix for sha accel seq constraint solver
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sha_accel_sequence.svh
Labels: regression

#473 Remove duplicate LMS tests from regression
  src/integration/stimulus/testsuites/caliptra_top_nightly_directed_regression.yml
Labels: Environment, regression

#477 [UVM] Fix regression failure caused by a false negative
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_dlen_invalid_sequence.svh
Labels: regression

#455 Update CaliptraIntegrationSpecification.md
  docs/CaliptraIntegrationSpecification.md
Labels: documentation

#480 revised rdl comments
  src/ecc/rtl/ecc_reg.rdl
  src/hmac/rtl/hmac_reg.rdl
  src/sha256/rtl/sha256_reg.rdl
  src/sha512/rtl/sha512_reg.rdl
Labels: documentation

#482 [UVM] Implement mailbox sanitize feature in val fw to suppress regression failure
  src/integration/test_suites/caliptra_rt/caliptra_rt.c
  src/integration/test_suites/libs/soc_ifc/soc_ifc.c
  src/integration/test_suites/libs/soc_ifc/soc_ifc.h
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sram_double_bit_flip_sequence.svh
Labels: regression
