Repository chipsalliance/caliptra-rtl, pull requests merged in 2024-05, with the labels that each got.

#510 Resolving unnamed generate blocks Lint warnings
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  src/riscv_core/veer_el2/rtl/dec/el2_dec_decode_ctl.sv
  src/riscv_core/veer_el2/rtl/dec/el2_dec_tlu_ctl.sv
  src/riscv_core/veer_el2/rtl/dec/el2_dec_trigger.sv
  src/riscv_core/veer_el2/rtl/exu/el2_exu_div_ctl.sv
  src/riscv_core/veer_el2/rtl/ifu/el2_ifu_aln_ctl.sv
  src/riscv_core/veer_el2/rtl/ifu/el2_ifu_bp_ctl.sv
  src/riscv_core/veer_el2/rtl/ifu/el2_ifu_ifc_ctl.sv
  src/riscv_core/veer_el2/rtl/lib/beh_lib.sv
  src/riscv_core/veer_el2/rtl/lsu/el2_lsu_bus_buffer.sv
  src/riscv_core/veer_el2/rtl/lsu/el2_lsu_trigger.sv
Labels: enhancement

#511 Documentation update for RDC
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  README.md
  docs/CaliptraIntegrationSpecification.md
  docs/images/Reset_structure.png
  docs/images/Thumbs.db
  docs/images/entropy_RDC.png
  docs/images/halt_status_rdc.png
  docs/images/reset_ordering.png
  docs/images/reset_sequencing.png
Labels: documentation

#514 [UVM] Update validation firmware to force unlock mailbox when sanitizing
  .github/workflow_metadata/pr_hash
  .github/workflow_metadata/pr_timestamp
  src/integration/test_suites/libs/soc_ifc/soc_ifc.c
  src/integration/uvmf_caliptra_top/uvmf_template_output/project_benches/caliptra_top/tb/sequences/src/caliptra_top_rand_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sequence_base.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/sequences/mbox/soc_ifc/soc_ifc_env_mbox_sram_double_bit_flip_sequence.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/environment_packages/soc_ifc_env_pkg/src/soc_ifc_env_typedefs.svh
  src/soc_ifc/uvmf_soc_ifc/uvmf_template_output/verification_ip/interface_packages/mbox_sram_pkg/src/mbox_sram_driver_bfm.sv
Labels: regression
