Repository chipsalliance/caliptra-rtl, pull requests merged in 2024-01, with the labels that each got.

#377 Fix usage of RISC-V toolchain
  .github/scripts/gdb_test.sh
  .github/workflows/build-test-verilator.yml
  .github/workflows/interactive-debugging.yml
  README.md
  src/integration/test_suites/fw_test_rom/fw_test_rom.makefile
  src/integration/test_suites/infinite_loop/dump_and_compare.sh
  src/integration/test_suites/infinite_loop/mem_access.sh
  src/integration/test_suites/infinite_loop/peripheral_access.sh
  tools/scripts/Makefile
Labels: Environment

#372 Add RTL file list to be modified by integrators
  docs/CaliptraIntegrationSpecification.md
Labels: documentation

#385 Update documentation version numbers from 1.0-rc2 to 1.0
  README.md
  Release_Notes.md
  docs/CaliptraHardwareSpecification.md
  docs/CaliptraIntegrationSpecification.md
Labels: documentation, 1.0 spec final docs
